// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/me": {
    params: {};
  };
  "/calculators/derivative": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/me" | "/calculators/derivative" | "/login" | "/register" | "/forgot-password";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/me.tsx": {
    id: "routes/me";
    page: "/me";
  };
  "routes/calculators/derivative.tsx": {
    id: "routes/calculators/derivative";
    page: "/calculators/derivative";
  };
  "routes/auth-layout.tsx": {
    id: "routes/auth-layout";
    page: "/login" | "/register" | "/forgot-password";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/me": typeof import("./app/routes/me.tsx");
  "routes/calculators/derivative": typeof import("./app/routes/calculators/derivative.tsx");
  "routes/auth-layout": typeof import("./app/routes/auth-layout.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
};